// "AI-drafted email" tab — header strip with eval chips, the email envelope,
// and the action bar (approve / edit / regenerate).
import { useEffect, useState } from "react";
import type { InboxCustomerDetail } from "../api";
import { relTime } from "./inbox.utils";
import { Chip } from "./ui";
import { EmailEnvelope } from "./EmailEnvelope";

export function EmailDraftView({
  detail,
  isSent,
  onSend,
}: {
  detail: InboxCustomerDetail;
  isSent: boolean;
  onSend: () => void;
}) {
  const { email, eval: ev } = detail;
  const [edit, setEdit] = useState(false);
  // Bumping the key remounts the envelope — used to revert edits on Esc.
  const [envelopeKey, setEnvelopeKey] = useState(0);
  const [hint, setHint] = useState<string>();

  // Esc while editing → revert the body and exit edit mode.
  useEffect(() => {
    if (!edit) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        setEdit(false);
        setEnvelopeKey((k) => k + 1);
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [edit]);

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="font-mono text-[10.5px] uppercase tracking-[1.4px] text-[var(--muted)]">
            Grounded in · {email.grounded_on}
          </div>
          <div className="mt-0.5 text-[13.5px] font-medium text-[var(--fg-soft)]">
            Generated by {email.generated_by} · evidence-grounded ·{" "}
            {relTime(email.generated_at)}
          </div>
        </div>
        <div className="flex shrink-0 gap-1.5">
          <Chip tone="ok">DistilBERT {ev.distilbert_score} / 5</Chip>
          <Chip tone="info">Judge {ev.judge_score} / 5</Chip>
        </div>
      </div>

      <EmailEnvelope key={envelopeKey} email={email} edit={edit} />

      {hint && <p className="text-[11.5px] text-[var(--muted)]">{hint}</p>}

      <div className="flex items-center gap-2">
        <button
          type="button"
          disabled={isSent}
          onClick={onSend}
          className="rounded-md px-4 py-2.5 text-[13px] font-semibold transition disabled:cursor-default"
          style={
            isSent
              ? { background: "var(--ok-bg)", color: "var(--ok)" }
              : { background: "var(--accent)", color: "var(--on-accent)" }
          }
        >
          {isSent ? "✓ Sent · awaiting reply" : "Approve & send"}
        </button>
        <button
          type="button"
          onClick={() => setEdit((e) => !e)}
          className="rounded-md border border-[var(--line)] bg-[var(--surface)] px-3 py-2.5 text-[13px] font-medium text-[var(--fg)] transition hover:border-[var(--fg-mute)]"
        >
          {edit ? "Save edits" : "Edit copy"}
        </button>
        <button
          type="button"
          onClick={() =>
            setHint("Would re-call claude-opus-4-5 — regenerate is wired in v1.1.")
          }
          className="rounded-md border border-[var(--line)] bg-[var(--surface)] px-3 py-2.5 text-[13px] font-medium text-[var(--fg)] transition hover:border-[var(--fg-mute)]"
        >
          Regenerate
        </button>
        <div className="flex-1" />
        <span className="text-[11.5px] text-[var(--muted)]">
          Schedule:{" "}
          <b className="font-medium text-[var(--fg-soft)]">send now</b>
        </span>
      </div>
    </div>
  );
}
